name: ci
on:
  pull_request:

jobs:
  tests:
    name: Unit Tests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: './go.mod'
      - name: Run Unit Tests
        run: |
          make unit_test
      - name: Run Integration Tests
        run: |
          make integration_test
      - name: Build
        run: |
          make build
